# Generated by Django 6.0.3 on 2026-04-30 07:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CookieGroupModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the cookie group (e.g., 'Necessary', 'Analytics').",
                        max_length=255,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "varname",
                    models.SlugField(
                        help_text="A URL-safe identifier for this cookie group (auto-generated from name if not provided).",
                        max_length=255,
                        unique=True,
                        verbose_name="Variable Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A brief description of the cookie group.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, this cookie group is required and users cannot decline it. Use for essential cookies like session or CSRF.",
                        verbose_name="Required",
                    ),
                ),
                (
                    "is_deletable",
                    models.BooleanField(
                        default=True,
                        help_text="If checked, cookies in this group will be automatically deleted when the user declines or withdraws consent.",
                        verbose_name="Deletable",
                    ),
                ),
                (
                    "ordering",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The order in which this group appears in the consent dialog. Lower numbers appear first.",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the group was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp when the group was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cookie Group",
                "verbose_name_plural": "Cookie Groups",
                "ordering": ["ordering", "name"],
            },
        ),
        migrations.CreateModel(
            name="CookiePolicyModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="The version of the cookie policy.",
                        max_length=50,
                        unique=True,
                        verbose_name="Version",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The content of the cookie policy.",
                        verbose_name="Content",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this policy version is active. Only one policy should be active at a time.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True,
                        help_text="The date when this policy becomes effective.",
                        null=True,
                        verbose_name="Effective Date",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the policy was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp when the policy was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cookie Policy",
                "verbose_name_plural": "Cookie Policies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CookieModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the cookie.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A brief description of the cookie's purpose.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        help_text="The domain for which the cookie is valid.",
                        max_length=255,
                        null=True,
                        verbose_name="Domain",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        default="/",
                        help_text="The path for which the cookie is valid.",
                        max_length=255,
                        verbose_name="Path",
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="The value stored in the cookie.",
                        verbose_name="Value",
                    ),
                ),
                (
                    "expires",
                    models.DateTimeField(
                        blank=True,
                        help_text="The expiration date and time of the cookie.",
                        null=True,
                        verbose_name="Expiration Date",
                    ),
                ),
                (
                    "secure",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the cookie is secure (sent only over HTTPS).",
                        verbose_name="Secure",
                    ),
                ),
                (
                    "httponly",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the cookie is HTTPOnly (not accessible via JavaScript).",
                        verbose_name="HTTPOnly",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the cookie was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp when the cookie was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "cookiegroup",
                    models.ForeignKey(
                        help_text="The group to which this cookie belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cookie_set",
                        to="cookie.cookiegroupmodel",
                        verbose_name="Cookie Group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cookie",
                "verbose_name_plural": "Cookies",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cookiegroup", "name", "domain"),
                        name="unique_cookie_constraint",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CookieConsentModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="The session key for anonymous users.",
                        max_length=40,
                        null=True,
                        verbose_name="Session Key",
                    ),
                ),
                (
                    "necessary",
                    models.BooleanField(
                        default=True,
                        help_text="Consent for necessary cookies.",
                        verbose_name="Necessary",
                    ),
                ),
                (
                    "analytics",
                    models.BooleanField(
                        default=False,
                        help_text="Consent for analytics cookies.",
                        verbose_name="Analytics",
                    ),
                ),
                (
                    "marketing",
                    models.BooleanField(
                        default=False,
                        help_text="Consent for marketing cookies.",
                        verbose_name="Marketing",
                    ),
                ),
                (
                    "consent_given",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the user has given overall cookie consent.",
                        verbose_name="Consent Given",
                    ),
                ),
                (
                    "consent_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The timestamp when the user last updated their consent.",
                        verbose_name="Consent Date",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="The IP address when consent was given.",
                        null=True,
                        verbose_name="IP Address",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the consent record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp when the consent record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="The authenticated user who provided consent.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cookie_consent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "policy_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="The cookie policy version the user consented to. When a new policy is published, users may need to re-consent.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consents",
                        to="cookie.cookiepolicymodel",
                        verbose_name="Policy Version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cookie Consent",
                "verbose_name_plural": "Cookie Consents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["session_key"], name="consent_session_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("user__isnull", False),
                            ("session_key__isnull", False),
                            _connector="OR",
                        ),
                        name="consent_requires_user_or_session",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LogItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("accepted", "Accepted"), ("declined", "Declined")],
                        help_text="The consent action taken by the user.",
                        max_length=10,
                        verbose_name="Action",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="The session key for anonymous users.",
                        max_length=40,
                        null=True,
                        verbose_name="Session Key",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="The IP address of the user.",
                        null=True,
                        verbose_name="IP Address",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="The user agent string of the browser.",
                        null=True,
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="The cookie group version at the time of consent. Used to verify valid consent for specific cookie versions.",
                        max_length=50,
                        null=True,
                        verbose_name="Version",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The timestamp when the action was taken.",
                        verbose_name="Timestamp",
                    ),
                ),
                (
                    "cookiegroup",
                    models.ForeignKey(
                        help_text="The cookie group for which consent was given.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_items",
                        to="cookie.cookiegroupmodel",
                        verbose_name="Cookie Group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The authenticated user who gave consent (if any).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cookie_consent_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent Log",
                "verbose_name_plural": "Consent Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "cookiegroup"], name="logitem_user_group_idx"
                    ),
                    models.Index(
                        fields=["session_key", "cookiegroup"],
                        name="logitem_session_group_idx",
                    ),
                ],
            },
        ),
    ]
